import type { TokenFilterConfig, TrendingBotStrategy } from './types'

export const DEFAULT_FILTER_CONFIG: TokenFilterConfig = {
  enabled: true,
  mcap: { min: 350_000, max: 3_000_000 },
  priceChange5m: { max: -40.0 },
  priceChange1h: { max: 100.0 },
  priceChange6h: { max: 60.0 },
  organicScore: { min: 70 },
  topHoldersPercentage: { max: 25 },
  requireCompleteData: true,
  checkManualTradingHistory: true,
}

export const TRENDING_BOT_STRATEGIES: Record<string, TrendingBotStrategy> = {
  att: {
    id: 'att',
    name: 'Attention Strategy',
    description: 'Original aggressive trading strategy',
    is_active: true,
    take_profit_levels: {
      tp1_percentage: 45,
      tp1_sell_percentage: 90,
      tp2_percentage: 100,
      tp3_percentage: 30,
      tp3_enabled: false,
    },
    buy_amount_sol: 0.035,
    priority_fee_lamports: 1_000_000,
    stop_loss_percentage: -35,
    max_hold_hours: 24,
    conditions: { max_risk_level: 'high' },
    filtering: {
      enabled: true,
      mcap: { min: 200_000, max: 5_000_000 },
      priceChange5m: { max: -50.0 },
      priceChange1h: { max: 150.0 },
      priceChange6h: { max: 80.0 },
      organicScore: { min: 60 },
      topHoldersPercentage: { max: 30 },
      requireCompleteData: true,
      checkManualTradingHistory: true,
    },
  },
  lowcap_moonbag: {
    id: 'lowcap_moonbag',
    name: 'low cap potentail moonback',
    description: 'Lower risk, steady gains approach',
    is_active: true,
    take_profit_levels: {
      tp1_percentage: 200,
      tp1_sell_percentage: 90,
      tp2_percentage: 400,
      tp3_percentage: 600,
      tp3_enabled: true,
    },
    buy_amount_sol: 0.008,
    priority_fee_lamports: 1_000_000,
    stop_loss_percentage: -30,
    max_hold_hours: 12,
    conditions: {
      min_market_cap: 35_000,
      max_market_cap: 90_000,
      min_organic_score: 0,
      max_risk_level: 'low',
    },
    filtering: {
      enabled: true,
      mcap: { min: 35_000, max: 90_000 },
      priceChange5m: { max: -25.0 },
      priceChange1h: { max: 600.0 },
      priceChange6h: { max: 600.0 },
      organicScore: { min: 0 },
      topHoldersPercentage: { max: 25 },
      requireCompleteData: true,
      checkManualTradingHistory: true,
    },
  },
  scalper: {
    id: 'scalper',
    name: 'Scalping Strategy',
    description: 'Quick profits, fast exits',
    is_active: false,
    take_profit_levels: {
      tp1_percentage: 15,
      tp1_sell_percentage: 90,
      tp2_percentage: 25,
      tp3_percentage: 40,
      tp3_enabled: true,
    },
    buy_amount_sol: 0.008,
    priority_fee_lamports: 1_000_000,
    stop_loss_percentage: -15,
    max_hold_hours: 6,
    conditions: { max_risk_level: 'medium' },
    filtering: {
      enabled: true,
      mcap: { min: 300_000, max: 4_000_000 },
      priceChange5m: { min: -30.0, max: -10.0 },
      priceChange1h: { min: 20.0, max: 80.0 },
      priceChange6h: { max: 70.0 },
      organicScore: { min: 65 },
      topHoldersPercentage: { max: 25 },
      requireCompleteData: true,
      checkManualTradingHistory: true,
    },
  },
  hodl: {
    id: 'hodl',
    name: 'HODL Strategy',
    description: 'Long-term holding strategy',
    is_active: false,
    take_profit_levels: {
      tp1_percentage: 100,
      tp1_sell_percentage: 25,
      tp2_percentage: 200,
      tp3_percentage: 500,
      tp3_enabled: true,
    },
    buy_amount_sol: 0.006,
    priority_fee_lamports: 1_000_000,
    stop_loss_percentage: -60,
    max_hold_hours: 168,
    conditions: {
      min_market_cap: 500_000,
      min_organic_score: 80,
      max_risk_level: 'low',
    },
    filtering: {
      enabled: true,
      mcap: { min: 1_000_000, max: 10_000_000 },
      priceChange5m: { max: -20.0 },
      priceChange1h: { max: 30.0 },
      priceChange6h: { max: 50.0 },
      organicScore: { min: 85 },
      topHoldersPercentage: { max: 15 },
      requireCompleteData: true,
      checkManualTradingHistory: true,
    },
  },
}

export const SIGNALS_STRATEGY_META = [
  {
    id: 'default' as const,
    name: 'Default momentum',
    description: 'Enter on strong growth + score ≥ 50',
    params: { minGrowthDefault: 0, recencyMinutesDefault: 240, enterScoreFloor: 50 },
  },
  {
    id: 'sell_over_100' as const,
    name: 'Sell over 100%',
    description: 'Favor exit above 100% growth; penalize late surges',
    params: { minGrowthDefault: 0, recencyMinutesDefault: 240, enterScoreFloor: 50 },
  },
]
