#!/bin/bash

# install-deploy-hook.sh
# Installs a Git post-merge hook that automatically builds & deploys reloadSOL
# using scripts/deploy-single-core.sh whenever `git pull` brings new commits.

set -euo pipefail

HOOK_FILE=".git/hooks/post-merge"
DEPLOY_SCRIPT="$(dirname "$0")/deploy-single-core.sh"

if [ ! -f "$DEPLOY_SCRIPT" ]; then
  echo "❌ deploy-single-core.sh not found at $DEPLOY_SCRIPT"
  exit 1
fi

cat > "$HOOK_FILE" <<EOF
#!/bin/bash
# Auto-deploy hook generated by install-deploy-hook.sh
exec "$(dirname "$0")/deploy-update.sh" "${@:-}"
EOF

chmod +x "$HOOK_FILE"

echo "✅ Git post-merge hook installed. Any future \`git pull\` will trigger the deployment script." 