#!/usr/bin/env bash
# install-docker-deploy-hook.sh
# Installs a Git post-merge hook that runs docker-deploy.sh after `git pull`.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

HOOK_FILE=".git/hooks/post-merge"
DEPLOY_SCRIPT="$ROOT/scripts/docker-deploy.sh"

if [[ ! -f "$DEPLOY_SCRIPT" ]]; then
  echo "Missing $DEPLOY_SCRIPT"
  exit 1
fi

chmod +x "$DEPLOY_SCRIPT"

cat > "$HOOK_FILE" <<EOF
#!/bin/bash
# Auto Docker deploy — generated by install-docker-deploy-hook.sh
set -euo pipefail

cd "$ROOT"

# post-merge only fires when HEAD moved (new commits pulled)
PREV="\${1:-}"
if [[ -n "\$PREV" ]] && [[ "\$(git rev-parse HEAD)" == "\$PREV" ]]; then
  exit 0
fi

exec "$DEPLOY_SCRIPT" --skip-pull
EOF

chmod +x "$HOOK_FILE"

echo "Git post-merge hook installed."
echo "Every 'git pull' that brings new commits will run: $DEPLOY_SCRIPT --skip-pull"
